### ISSUE TITLE
> Mam projekt bazy ogniowej w UE, ale kiedy stackblitz wdraża, próbuje tak zrobić w regionie USA i kończy się niepowodzeniem. Prawdopodobnie powinno to być przezroczyste lub przynajmniej konfigurowalne.

### ISSUE THREAD

**Issue by mtrackeros** [stackblitz/ng-be-workshop#2]
> Mam projekt bazy ogniowej w UE, ale kiedy stackblitz wdraża, próbuje tak zrobić w regionie USA i kończy się niepowodzeniem. Prawdopodobnie powinno to być przezroczyste lub przynajmniej konfigurowalne.

_Originally posted by @mtrackeros in https://github.com/stackblitz/core/issues/2157#issuecomment-1312407106_

**Comment by d3lm** [comment]
Hey there! Sorry but if there's an issue please provide a proper title (in English) and a description that includes a reproduction.

**Comment by mtrackeros** [comment]
> I have a firebase project in the EU, but when stackblitz implements, it tries to do so in the US region and fails. This should probably be transparent or at least customizable.
